---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Find EXTERNALLY-MANAGED files
      ansible.builtin.find:
        paths: /usr/lib
        patterns: "EXTERNALLY-MANAGED"
        recurse: true
      register: externally_managed_files

    - name: Remove EXTERNALLY-MANAGED files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ externally_managed_files.files }}"

  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.epel
    - role: buluma.python_pip
    - role: buluma.buildtools
    - openssl_items:
        - common_name: "{{ ansible_facts['fqdn'] }}"
          name: apache-httpd
      role: buluma.openssl
    - role: buluma.httpd
    - role: buluma.php
    - mysql_databases:
        - name: mediawiki
      mysql_users:
        - name: mediawiki
          password: m3d14w1k1
          priv: mediawiki.*:ALL
      role: buluma.mysql
