---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - ansible.builtin.get_url:
        dest: /tmp/whatever
        url: http://localhost/mediawiki
      name: connect to mediawiki
